import axelrod as axl

STRATEGIES = [axl.Cooperator(), axl.Alternator(), axl.BackStabber()]

# COMAPANY
COMPANY_RESOURCES_MIN = 1000
COMPANY_RESOURCES_MAX = 1000000
COMPANY_HEADCOUNT_MIN = 10
COMPANY_HEADCOUNT_MAX = 20

# NUMBER OF ROUNDS
NUM_ROUNDS = 2


NUM_TEAMS = 3
